import {
  Card,
  CardContent,
  Typography,
  Grid,
  Button,
  LinearProgress,
  Chip,
  Stack,
  Box,
} from "@mui/material";

import AutoAwesomeIcon from "@mui/icons-material/AutoAwesome";
import StarIcon from "@mui/icons-material/Star";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";

import { Link } from "react-router-dom";

import { calculateSimilarity } from "../../utils/similarityEngine";

function SimilarPlanets({ currentPlanet, planets }) {

  if (!planets || planets.length === 0) return null;

  return (

    <Box sx={{ mt: 6 }}>

      <Typography
        variant="h4"
        fontWeight={700}
        gutterBottom
      >
        🤖 AI Recommended Planets
      </Typography>

      <Typography
        color="text.secondary"
        sx={{ mb: 4 }}
      >
        Recommendations generated by comparing planetary
        characteristics with the selected planet.
      </Typography>

      <Grid container spacing={3}>

        {planets.map((planet, index) => {

          const similarity =
            calculateSimilarity(
              currentPlanet,
              planet
            );

          return (

            <Grid
              item
              xs={12}
              md={4}
              key={planet.id}
            >

              <Card
                sx={{
                  height: "100%",
                  borderRadius: 4,

                  background:
                    "rgba(255,255,255,.04)",

                  backdropFilter:
                    "blur(10px)",

                  border:
                    index === 0
                      ? "2px solid gold"
                      : "1px solid rgba(255,255,255,.08)",

                  transition: ".35s",

                  "&:hover": {
                    transform:
                      "translateY(-8px)",
                    boxShadow: 8,
                  },
                }}
              >

                <CardContent>

                  {index === 0 && (

                    <Chip
                      icon={<StarIcon />}
                      label="BEST MATCH"
                      color="warning"
                      sx={{
                        mb: 2,
                        fontWeight: 700,
                      }}
                    />

                  )}

                  <Typography
                    variant="h5"
                    fontWeight={700}
                  >
                    {planet.planet_name}
                  </Typography>

                  <Typography
                    color="text.secondary"
                    mb={3}
                  >
                    {planet.host_star}
                  </Typography>

                  <Stack
                    direction="row"
                    spacing={1}
                    alignItems="center"
                    mb={1}
                  >

                    <AutoAwesomeIcon
                      color="primary"
                    />

                    <Typography
                      fontWeight={700}
                    >
                      {similarity.summary}
                    </Typography>

                  </Stack>

                  <Typography
                    color="primary"
                    fontWeight={700}
                    mb={1}
                  >
                    Similarity
                    {" "}
                    {similarity.similarity}%
                  </Typography>

                  <LinearProgress
                    variant="determinate"
                    value={similarity.similarity}
                    sx={{
                      height: 10,
                      borderRadius: 10,
                      mb: 3,
                    }}
                  />

                  <Typography
                    fontWeight={700}
                    gutterBottom
                  >
                    Why this planet?
                  </Typography>

                  {similarity.reasons.map(
                    (reason, i) => (

                      <Typography
                        key={i}
                        color="text.secondary"
                        sx={{
                          mb: .7,
                        }}
                      >
                        ✓ {reason}
                      </Typography>

                    )
                  )}

                  <Button
                    component={Link}
                    to={`/planet/${planet.id}`}
                    variant="contained"
                    endIcon={<ArrowForwardIcon />}
                    sx={{
                      mt: 3,
                      borderRadius: 3,
                    }}
                    fullWidth
                  >
                    View Planet
                  </Button>

                </CardContent>

              </Card>

            </Grid>

          );

        })}

      </Grid>

    </Box>

  );

}

export default SimilarPlanets;