import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function getSummary(score) {

  if (score >= 85) {
    return "Excellent habitability potential. Multiple planetary characteristics resemble Earth and suggest favorable conditions for life.";
  }

  if (score >= 70) {
    return "Good habitability potential. Several important Earth-like characteristics are present, although some factors reduce confidence.";
  }

  if (score >= 50) {
    return "Moderate habitability potential. The planet has a mix of favorable and unfavorable characteristics.";
  }

  return "Low habitability potential. Most planetary characteristics differ significantly from Earth-like conditions.";

}

export function exportPlanetReport(
  planet,
  habitabilityScore,
  explanation
) {

  const doc = new jsPDF();

  const pageWidth =
    doc.internal.pageSize.getWidth();

  //----------------------------------------
  // Header
  //----------------------------------------

  doc.setFillColor(20,35,70);

  doc.rect(
    0,
    0,
    pageWidth,
    28,
    "F"
  );

  doc.setTextColor(255,255,255);

  doc.setFontSize(22);

  doc.text(
    "Exoplanet Intelligence Report",
    14,
    18
  );

  //----------------------------------------

  doc.setTextColor(0,0,0);

  doc.setFontSize(11);

  doc.text(
    "Generated by Exoplanet Discovery & Habitability Intelligence Platform",
    14,
    38
  );

  //----------------------------------------
  // Planet Information
  //----------------------------------------

  autoTable(doc,{
    startY:48,

    head:[
      ["Planet Information","Value"]
    ],

    body:[

      ["Planet",planet.planet_name],

      ["Discovery Method",planet.discovery_method],

      ["Discovery Year",planet.discovery_year],

      ["Host Star",planet.host_star],

      ["Distance (pc)",planet.distance_pc ?? "-"]

    ],

    headStyles:{
      fillColor:[37,99,235]
    }

  });

  //----------------------------------------
  // Habitability
  //----------------------------------------

  autoTable(doc,{

    startY:doc.lastAutoTable.finalY+8,

    head:[
      ["Habitability","Value"]
    ],

    body:[

      [
        "Overall Score",
        `${habitabilityScore}/100`
      ],

      [
        "AI Summary",
        getSummary(habitabilityScore)
      ]

    ],

    headStyles:{
      fillColor:[22,163,74]
    }

  });

  //----------------------------------------
  // Breakdown
  //----------------------------------------

  autoTable(doc,{

    startY:doc.lastAutoTable.finalY+8,

    head:[
      [
        "Factor",
        "Score",
        "Explanation"
      ]
    ],

    body:
      explanation.breakdown.map(item => [

        item.title,

        `+${item.score}`,

        item.reason

      ]),

    headStyles:{
      fillColor:[124,58,237]
    }

  });

  //----------------------------------------
  // Planet Properties
  //----------------------------------------

  autoTable(doc,{

    startY:doc.lastAutoTable.finalY+8,

    head:[
      ["Planet Properties","Value"]
    ],

    body:[

      [
        "Planet Mass",
        planet.planet_mass_earth ?? "-"
      ],

      [
        "Planet Radius",
        planet.planet_radius_earth ?? "-"
      ],

      [
        "Orbital Period",
        planet.orbital_period_days ?? "-"
      ],

      [
        "Equilibrium Temperature",
        planet.equilibrium_temperature ?? "-"
      ]

    ],

    headStyles:{
      fillColor:[234,88,12]
    }

  });

  //----------------------------------------
  // Star
  //----------------------------------------

  autoTable(doc,{

    startY:doc.lastAutoTable.finalY+8,

    head:[
      ["Host Star","Value"]
    ],

    body:[

      [
        "Star Mass",
        planet.star_mass ?? "-"
      ],

      [
        "Star Radius",
        planet.star_radius ?? "-"
      ],

      [
        "Star Temperature",
        planet.star_temperature ?? "-"
      ]

    ],

    headStyles:{
      fillColor:[14,165,233]
    }

  });

  //----------------------------------------

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    `Generated on ${new Date().toLocaleString()}`,
    14,
    285
  );

  doc.save(
    `${planet.planet_name}_Report.pdf`
  );

}